name: Deploy to Local IIS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # Windows Server üzerinde çalışacak

    steps:
      - name: Kodu Checkout Et
        uses: actions/checkout@v3

      - name: .NET 9.0 Kurulumu
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Bağımlılıkları Yükle
        run: dotnet restore

      - name: Projeyi Build Et
        run: dotnet publish -c Release -o ./publish

      - name: IIS wwwroot’a Kopyala
        run: |
          robocopy ./publish C:\inetpub\wwwroot\webapi /E /XO

      - name: IIS'i Yeniden Başlat
        run: |
          iisreset
