name: Deploy to Local IIS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Kodu Checkout Et
        uses: actions/checkout@v3

      - name: .NET 9.0 Kurulumu
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Bağımlılıkları Yükle
        run: dotnet restore

      - name: Projeyi Build Et
        run: dotnet publish -c Release -o ./publish

      - name: Publish Klasörünü Kontrol Et
        run: ls ./publish

      - name: IIS'i Durdur
        run: |
          iisreset /stop
          sleep 5

      - name: Yetkileri Ayarla
        run: |
          icacls "C:\inetpub\wwwroot\webapi" /grant Everyone:F /T /C /Q

      - name: IIS wwwroot’a Kopyala
        shell: powershell
        run: |
          robocopy ./publish C:\inetpub\wwwroot\ci_cd_api /E /XO
          if ($LASTEXITCODE -eq 1) { exit 0 }


      - name: IIS'i Başlat
        run: |
          iisreset /start
